version: 1
date: 2026-07-04
title: 数据结构第一章学习笔记
theme: clean

jobs:
  - id: data-structure-chapter1-notes
    type: single
    title: 数据结构第一章学习笔记
    input: md/001-数据结构第一章学习笔记.md
    output: 数据结构第一章学习笔记.pdf
