version: 1
date: 2026-07-04
title: 计算机网络第六章学习笔记整理
theme: clean

jobs:
  - id: cn-network-chapter-6
    type: single
    title: 计算机网络第六章学习笔记
    input: md/001-计算机网络第六章学习笔记.md
    output: 计算机网络第六章学习笔记.pdf
