version: 1
date: 2026-07-04
title: 2026-07-04 计算机组成原理第5-6章学习笔记
theme: clean

jobs:
  - id: comp-org-ch5-6-notes
    type: single
    title: 计算机组成原理第5-6章学习笔记
    input: md/001-计算机组成原理第5-6章学习笔记.md
    output: 2026-07-04-计算机组成原理第5-6章学习笔记.pdf
