version: 1
date: 2026-07-04
title: 2026-07-04 data-structure-chapter-4-notes
theme: clean

jobs:
  - id: data-structure-ch4-notes
    type: merge
    title: data-structure-chapter-4-notes
    inputs: all
    sort: filename
    page_break: false
    output: 2026-07-04-data-structure-chapter-4-notes.pdf
